import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/providers'
import { ToastContainer } from 'react-toastify'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ToastContainer />
        <Providers>
          <div className='flex min-h-dvh'>
            <div className='w-[20%] h-dvh bg-primary-blue text-white py-10 flex flex-col gap-10'>
              <h1 className='text-3xl font-bold px-5'>CMS</h1>
              <Sidebar />
            </div>
            <div className='w-[80%] min-h-dvh'>{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
